import {
  DoubleSide,
  EdgesGeometry,
  Group,
  LatheGeometry,
  LineBasicMaterial,
  LineSegments,
  Matrix4,
  Mesh,
  Vector2,
  Vector3,
} from "three";

// 360° surface of revolution generated by rotating a polyline around the line
// through its two endpoints. Hidden segments (indices in `hiddenSegmentsIdx`)
// are skipped: the polyline is split into runs of contiguous non-hidden
// segments and one LatheGeometry is built per run, all sharing the same axis
// frame. Per-vertex offsetBottom/offsetTop and arc segments
// (point.type === "circle") are intentionally ignored — out of scope for the
// v1 of the REVOLUTION shape3D. Caller must pass points already in
// basemap-local meters (z=0 in the basemap plane).

const EDGE_MATERIAL = new LineBasicMaterial({
  color: 0x000000,
  transparent: true,
  opacity: 0.5,
});

const SEGMENTS = 64;

export default function buildRevolutionMesh(
  points,
  material,
  verticalLift = 0,
  hiddenSegmentsIdx = []
) {
  if (!points || points.length < 2) return null;

  const P0 = new Vector3(points[0].x, points[0].y, 0);
  const Pn = new Vector3(
    points[points.length - 1].x,
    points[points.length - 1].y,
    0
  );

  const A = new Vector3().subVectors(Pn, P0);
  const axisLen = A.length();
  if (axisLen < 1e-6) return null;
  const Ahat = A.clone().multiplyScalar(1 / axisLen);

  // Profile in lathe-local frame: X = radius (perpendicular distance to axis),
  // Y = along-axis coordinate. THREE.LatheGeometry revolves this profile
  // around its local +Y axis.
  const profileAll = points.map((p) => {
    const Pi = new Vector3(p.x, p.y, 0);
    const d = new Vector3().subVectors(Pi, P0);
    const t = d.dot(Ahat);
    const proj = Ahat.clone().multiplyScalar(t);
    const perp = new Vector3().subVectors(d, proj);
    return new Vector2(perp.length(), t);
  });

  // Endpoints of the full polyline lie on the axis by definition — clamp.
  profileAll[0].x = 0;
  profileAll[profileAll.length - 1].x = 0;

  // Split into runs of contiguous non-hidden segments. Run boundaries
  // introduced by hidden segments are NOT clamped to radius 0.
  const hidden = new Set(hiddenSegmentsIdx ?? []);
  const runs = [];
  let current = [profileAll[0]];
  for (let i = 0; i < profileAll.length - 1; i++) {
    if (hidden.has(i)) {
      if (current.length >= 2) runs.push(current);
      current = [profileAll[i + 1]];
    } else {
      current.push(profileAll[i + 1]);
    }
  }
  if (current.length >= 2) runs.push(current);
  if (runs.length === 0) return null;

  // Shared orientation: lathe local +Y → world axis Ahat, origin at P0 + verticalLift.
  const up = Math.abs(Ahat.z) < 0.9 ? new Vector3(0, 0, 1) : new Vector3(1, 0, 0);
  const u = new Vector3().crossVectors(up, Ahat).normalize();
  const w = new Vector3().crossVectors(Ahat, u).normalize();
  const m = new Matrix4().makeBasis(u, Ahat, w);
  m.setPosition(P0.x, P0.y, verticalLift);

  const surfMat = material.clone();
  surfMat.side = DoubleSide;

  const group = new Group();
  for (const run of runs) {
    const geom = new LatheGeometry(run, SEGMENTS);
    geom.applyMatrix4(m);
    geom.computeVertexNormals();
    group.add(new Mesh(geom, surfMat));
    group.add(new LineSegments(new EdgesGeometry(geom), EDGE_MATERIAL));
  }
  return group;
}
