import {
  DoubleSide,
  EdgesGeometry,
  Group,
  LatheGeometry,
  LineBasicMaterial,
  LineSegments,
  Mesh,
  Vector2,
} from "three";

// 360° surface of revolution generated by rotating an arc (the `arcPoints`
// polyline) around an axis ORTHOGONAL to the base map plane (its normal),
// placed in the scene at `centerLocal`.
//
// Geometry model (anchor-at-floor, per the feature spec):
//   - The revolution axis is the base map NORMAL: it stands the solid up off the
//     plane. In basemap-local space the normal is +Z for a HORIZONTAL base map
//     (which the parent group maps to world-up) and +Y for a VERTICAL one.
//   - radius(point)  = |arc.x − axisX|   (in-plane distance to the drawn axis)
//   - height(point)  = arc.y − baseY     (height above the axis bottom, shared
//                                         across arcs on the same axis)
//   - The profile is revolved with THREE.LatheGeometry (around its local +Y),
//     then re-oriented so the revolution axis matches the base map normal, then
//     translated to `centerLocal`.
//
// `centerLocal` is the in-plane position of the axis, taken from the linked
// REVOLUTION_POINT (resolved by useAnnotationsV2). When null (no point), the
// solid sits at the drawn axis's own location.
//
// Hidden segments (indices in `hiddenSegmentsIdx`) split the arc into runs of
// contiguous non-hidden segments, one LatheGeometry per run.
//
// Caller must pass arc/axis points already in basemap-local metres.

const EDGE_MATERIAL = new LineBasicMaterial({
  color: 0x000000,
  transparent: true,
  opacity: 0.5,
});

const SEGMENTS = 64;

export default function buildRevolutionMesh({
  arcPoints,
  axisPoints,
  centerLocal = null,
  orientation = "HORIZONTAL",
  material,
  hiddenSegmentsIdx = [],
}) {
  if (!arcPoints || arcPoints.length < 2) return null;
  if (!axisPoints || axisPoints.length < 2) return null;

  // Vertical-in-drawing axis position: average local x of the axis line.
  const axisX =
    axisPoints.reduce((sum, p) => sum + p.x, 0) / axisPoints.length;

  // Shared vertical reference = the axis line's bottom. Heights are measured
  // from it (NOT from each arc's own lowest point) so several arcs revolved
  // around the SAME axis keep their relative vertical positions instead of all
  // being anchored to the same base.
  const baseY = Math.min(...axisPoints.map((p) => p.y));

  // Profile in lathe-local frame: X = radius (distance to axis), Y = height
  // above the axis bottom.
  const profileAll = arcPoints.map(
    (p) => new Vector2(Math.abs(p.x - axisX), p.y - baseY)
  );

  // Split into runs of contiguous non-hidden segments.
  const hidden = new Set(hiddenSegmentsIdx ?? []);
  const runs = [];
  let current = [profileAll[0]];
  for (let i = 0; i < profileAll.length - 1; i++) {
    if (hidden.has(i)) {
      if (current.length >= 2) runs.push(current);
      current = [profileAll[i + 1]];
    } else {
      current.push(profileAll[i + 1]);
    }
  }
  if (current.length >= 2) runs.push(current);
  if (runs.length === 0) return null;

  // The revolution axis is the base map normal. For a HORIZONTAL base map that
  // is local +Z, so rotate the lathe (built around local +Y) by 90° about X so
  // its height runs along +Z. A VERTICAL base map already has its normal-aligned
  // up direction along local +Y, so no rotation is needed.
  const axisAlongNormal = orientation !== "VERTICAL";

  // In-plane placement of the axis. With a linked point, use it; otherwise fall
  // back to the drawn axis's own location.
  let center;
  if (centerLocal) {
    center = { x: centerLocal.x, y: centerLocal.y, z: centerLocal.z ?? 0 };
  } else if (axisAlongNormal) {
    const avgAxisY =
      axisPoints.reduce((sum, p) => sum + p.y, 0) / axisPoints.length;
    center = { x: axisX, y: avgAxisY, z: 0 };
  } else {
    center = { x: axisX, y: baseY, z: 0 };
  }

  const surfMat = material.clone();
  surfMat.side = DoubleSide;

  const group = new Group();
  for (const run of runs) {
    const geom = new LatheGeometry(run, SEGMENTS);
    if (axisAlongNormal) geom.rotateX(Math.PI / 2);
    geom.translate(center.x, center.y, center.z ?? 0);
    geom.computeVertexNormals();
    group.add(new Mesh(geom, surfMat));
    group.add(new LineSegments(new EdgesGeometry(geom), EDGE_MATERIAL));
  }
  return group;
}
