import {
  BufferGeometry,
  DoubleSide,
  EdgesGeometry,
  Float32BufferAttribute,
  Group,
  LatheGeometry,
  LineBasicMaterial,
  LineSegments,
  Mesh,
  MeshStandardMaterial,
  ShapeUtils,
  Vector2,
} from "three";
import { LineSegments2 } from "three/examples/jsm/lines/LineSegments2.js";
import { LineSegmentsGeometry } from "three/examples/jsm/lines/LineSegmentsGeometry.js";
import { LineMaterial } from "three/examples/jsm/lines/LineMaterial.js";

import { expandArcsInPathWithHiddenMap } from "Features/geometry/utils/arcSampling";

// 360° surface of revolution generated by rotating an arc (the `arcPoints`
// polyline) around an axis ORTHOGONAL to the base map plane (its normal),
// placed in the scene at `centerLocal`.
//
// Geometry model (anchor-at-floor, per the feature spec):
//   - The revolution axis is the base map NORMAL: it stands the solid up off the
//     plane. In basemap-local space the normal is +Z for a HORIZONTAL base map
//     (which the parent group maps to world-up) and +Y for a VERTICAL one.
//   - radius(point)  = |arc.x − axisX|   (in-plane distance to the drawn axis)
//   - height(point)  = arc.y − baseY     (height above the axis bottom, shared
//                                         across arcs on the same axis)
//   - The profile is revolved with THREE.LatheGeometry (around its local +Y),
//     then re-oriented so the revolution axis matches the base map normal, then
//     translated to `centerLocal`.
//
// `centerLocal` overrides the in-plane position of the axis. Callers pass null:
// the base map hosting the arc was POSED so its plane contains the axis (see
// computeVerticalBaseMapPlacementFromAxis), which is exactly the default here
// (z = 0 in the plane). Note that on a VERTICAL base map `baseY` cancels out
// (center.y = baseY, height = y − baseY), so the only load-bearing part of
// `axisPoints` is mean(x).
//
// Hidden segments (indices in `hiddenSegmentsIdx`) split the arc into runs of
// contiguous non-hidden segments, one LatheGeometry per run.
//
// Caller must pass arc/axis points already in basemap-local metres.

const EDGE_MATERIAL = new LineBasicMaterial({
  color: 0x000000,
  transparent: true,
  opacity: 0.5,
});

const SEGMENTS = 64;

// Section markers shown at the two sweep boundaries of a PARTIAL revolution so
// the profile reads like an architectural section drawing: ink-colored fat
// lines along the profile (always), plus an optional flat "poché" fill when
// the profile is a closed contour (sectionFill option). Ink color matches the
// aquarelle ink edges; lift matches STRIP_FOLD_LINE_LIFT.
const SECTION_INK_COLOR = 0x2a2a2a;
const SECTION_LINEWIDTH_PX = 2.5;
export const SECTION_MARKER_LIFT = 0.004;
// Profile first/last points closer than this (metres) = closed contour.
const SECTION_CLOSED_EPS = 1e-3;
const FULL_TURN_EPS = 1e-6;

// Lathe vertex formula at angle phi for a profile point (r, y), followed by
// the same frame ops applied to the lathe geometry: rotateX(π/2) when the
// revolution axis is the base map normal ((x, y, z) → (x, −z, y)), then the
// translation to `center`. Returns [x, y, z] plus a lift along the outward
// sweep tangent ±(cosφ, 0, −sinφ) so the marker never z-fights the surface.
//
// Exported so buildRevolutionCircleLine (POINT revolution) shares the EXACT
// same frame: a circle traced from a point lands right on the lathe surface of
// any arc revolved around the same axis. Pass outwardSign = 0 for no lift.
export function boundaryVertex(
  r,
  y,
  phi,
  outwardSign,
  axisAlongNormal,
  center
) {
  const lift = SECTION_MARKER_LIFT * outwardSign;
  let x = r * Math.sin(phi) + lift * Math.cos(phi);
  let yy = y;
  let z = r * Math.cos(phi) - lift * Math.sin(phi);
  if (axisAlongNormal) {
    const t = yy;
    yy = -z;
    z = t;
  }
  return [x + center.x, yy + center.y, z + (center.z ?? 0)];
}

// Sub-segments per S–C–S arc half when sampling a curved profile. An arc drawn
// as 3 anchor points (square→circle→square) would otherwise revolve as 2 straight
// chords; sampling makes the lathe follow the real curve.
const REVOLUTION_ARC_SAMPLES = 12;

export default function buildRevolutionMesh({
  arcPoints,
  axisPoints,
  centerLocal = null,
  orientation = "HORIZONTAL",
  material,
  hiddenSegmentsIdx = [],
  phiStart = 0,
  phiLength = Math.PI * 2,
  resolution = null,
  sectionFill = false,
}) {
  if (!arcPoints || arcPoints.length < 2) return null;
  if (!axisPoints || axisPoints.length < 2) return null;

  // Vertical-in-drawing axis position: average local x of the axis line.
  const axisX = axisPoints.reduce((sum, p) => sum + p.x, 0) / axisPoints.length;

  // Shared vertical reference = the axis line's bottom. Heights are measured
  // from it (NOT from each arc's own lowest point) so several arcs revolved
  // around the SAME axis keep their relative vertical positions instead of all
  // being anchored to the same base.
  const baseY = Math.min(...axisPoints.map((p) => p.y));

  // Sample S–C–S arcs in the profile so a curved arc revolves as a smooth
  // surface instead of straight chords. Hidden-segment indices are remapped
  // onto the densified point list.
  const { points: sampledArc, hiddenSegmentsIdx: sampledHidden } =
    expandArcsInPathWithHiddenMap(
      arcPoints,
      REVOLUTION_ARC_SAMPLES,
      hiddenSegmentsIdx ?? [],
      false
    );

  // Profile in lathe-local frame: X = radius (distance to axis), Y = height
  // above the axis bottom.
  const profileAll = sampledArc.map(
    (p) => new Vector2(Math.abs(p.x - axisX), p.y - baseY)
  );

  // Split into runs of contiguous non-hidden segments.
  const hidden = new Set(sampledHidden ?? []);
  const runs = [];
  let current = [profileAll[0]];
  for (let i = 0; i < profileAll.length - 1; i++) {
    if (hidden.has(i)) {
      if (current.length >= 2) runs.push(current);
      current = [profileAll[i + 1]];
    } else {
      current.push(profileAll[i + 1]);
    }
  }
  if (current.length >= 2) runs.push(current);
  if (runs.length === 0) return null;

  // The revolution axis is the base map normal. For a HORIZONTAL base map that
  // is local +Z, so rotate the lathe (built around local +Y) by 90° about X so
  // its height runs along +Z. A VERTICAL base map already has its normal-aligned
  // up direction along local +Y, so no rotation is needed.
  const axisAlongNormal = orientation !== "VERTICAL";

  // In-plane placement of the axis. With a linked point, use it; otherwise fall
  // back to the drawn axis's own location.
  let center;
  if (centerLocal) {
    center = { x: centerLocal.x, y: centerLocal.y, z: centerLocal.z ?? 0 };
  } else if (axisAlongNormal) {
    const avgAxisY =
      axisPoints.reduce((sum, p) => sum + p.y, 0) / axisPoints.length;
    center = { x: axisX, y: avgAxisY, z: 0 };
  } else {
    center = { x: axisX, y: baseY, z: 0 };
  }

  const surfMat = material.clone();
  surfMat.side = DoubleSide;

  // Keep tessellation density roughly constant when only a fraction of the
  // turn is swept (min a few segments so a thin wedge still reads as curved).
  const turnFraction = Math.min(1, Math.max(0, phiLength / (Math.PI * 2)));
  const segments = Math.max(4, Math.round(SEGMENTS * turnFraction));

  // Partial sweep → section markers at both boundaries. Per-call materials
  // (NEVER module singletons): carve/delete dispose child materials.
  const isPartial = phiLength < Math.PI * 2 - FULL_TURN_EPS;
  const phiEnd = phiStart + phiLength;
  let sectionLineMat = null;
  let sectionFillMat = null;
  if (isPartial) {
    sectionLineMat = new LineMaterial({
      color: SECTION_INK_COLOR,
      linewidth: SECTION_LINEWIDTH_PX,
      worldUnits: false,
      transparent: true,
    });
    if (resolution) sectionLineMat.resolution.set(resolution.x, resolution.y);
  }

  // Fat line along the profile at one sweep boundary. LineSegments2 is
  // `isMesh`: selection raycast must be disabled (aquarelle-edge pattern) and
  // `isSectionMarker` keeps it out of exports / plane sectioning.
  const buildBoundaryLine = (run, phi, outwardSign) => {
    const positions = [];
    for (let i = 0; i < run.length - 1; i++) {
      positions.push(
        ...boundaryVertex(
          run[i].x,
          run[i].y,
          phi,
          outwardSign,
          axisAlongNormal,
          center
        ),
        ...boundaryVertex(
          run[i + 1].x,
          run[i + 1].y,
          phi,
          outwardSign,
          axisAlongNormal,
          center
        )
      );
    }
    const geom = new LineSegmentsGeometry();
    geom.setPositions(positions);
    const line = new LineSegments2(geom, sectionLineMat);
    line.computeLineDistances();
    line.raycast = () => {};
    line.userData.isSectionMarker = true;
    // Boundary frame data consumed by refreshRevolutionSectionMarkers: after
    // a subtraction carve, the line is recomputed by sectioning the CARVED
    // geometry with this boundary plane, so intercepted openings interrupt
    // the profile trace instead of being drawn over.
    line.userData.sectionBoundary = {
      phi,
      outwardSign,
      axisAlongNormal,
      center: { x: center.x, y: center.y, z: center.z ?? 0 },
    };
    return line;
  };

  // Flat "poché" face filling the profile contour at one sweep boundary.
  const buildBoundaryFill = (run, faces, phi, outwardSign) => {
    const positions = [];
    for (const p of run) {
      positions.push(
        ...boundaryVertex(p.x, p.y, phi, outwardSign, axisAlongNormal, center)
      );
    }
    const geom = new BufferGeometry();
    geom.setAttribute("position", new Float32BufferAttribute(positions, 3));
    geom.setIndex(faces.flat());
    geom.computeVertexNormals();
    const mesh = new Mesh(geom, sectionFillMat);
    mesh.userData.isSectionMarker = true;
    return mesh;
  };

  const group = new Group();
  for (const run of runs) {
    const geom = new LatheGeometry(run, segments, phiStart, phiLength);
    if (axisAlongNormal) geom.rotateX(Math.PI / 2);
    geom.translate(center.x, center.y, center.z ?? 0);
    geom.computeVertexNormals();
    const mesh = new Mesh(geom, surfMat);
    // Tag every run so the carve pipeline finds ALL lathe surfaces (not just
    // the first mesh) — see getSolidMeshesFromObject3D.
    mesh.userData.role = "SOLID";
    group.add(mesh);
    group.add(new LineSegments(new EdgesGeometry(geom), EDGE_MATERIAL));

    if (!isPartial) continue;
    // Markers are children of the SOLID run mesh (not group siblings): the
    // carve pipeline strips root children that hold no SOLID mesh — see
    // subtractAnnotationGeometries.
    mesh.add(buildBoundaryLine(run, phiStart, -1));
    mesh.add(buildBoundaryLine(run, phiEnd, 1));

    const isClosed =
      run.length >= 4 &&
      run[0].distanceTo(run[run.length - 1]) < SECTION_CLOSED_EPS;
    if (sectionFill && isClosed) {
      // Drop the duplicate closing point for triangulation.
      const contour = run.slice(0, -1);
      let faces = null;
      try {
        faces = ShapeUtils.triangulateShape(contour, []);
      } catch {
        faces = null; // degenerate/self-intersecting contour: skip the fill
      }
      if (faces?.length) {
        if (!sectionFillMat) {
          sectionFillMat = new MeshStandardMaterial({
            color: SECTION_INK_COLOR,
            side: DoubleSide,
          });
        }
        mesh.add(buildBoundaryFill(contour, faces, phiStart, -1));
        mesh.add(buildBoundaryFill(contour, faces, phiEnd, 1));
      }
    }
  }
  return group;
}
