import getStripePolygons from "Features/geometry/utils/getStripePolygons";
import triangulateAnnotationGeometry from "Features/geometry/utils/triangulateAnnotationGeometry";

// True iff any point on the contour, any cut, or any innerPoint carries a
// non-zero offsetBottom / offsetTop. Used to gate the per-vertex-Z surface
// computation. Inner points alone (no offsets) don't trigger this — a flat
// inner point doesn't deform the surface so the planar shoelace stays exact.
function hasPerVertexZOffsets(annotation) {
  const ringHas = (ring) =>
    (ring || []).some(
      (p) => (p?.offsetBottom ?? 0) !== 0 || (p?.offsetTop ?? 0) !== 0
    );
  if (ringHas(annotation?.points)) return true;
  if (Array.isArray(annotation?.cuts)) {
    for (const c of annotation.cuts) {
      if (ringHas(c?.points)) return true;
    }
  }
  if (ringHas(annotation?.innerPoints)) return true;
  return false;
}

/**
 * --- HELPERS GÉOMÉTRIQUES ---
 */

const getDistance = (p1, p2) => {
  if (!p1 || !p2) return 0;
  return Math.hypot(p2.x - p1.x, p2.y - p1.y);
};

function getPointToLineDistance(p, a, b) {
  try {
    const numerator = Math.abs((b.x - a.x) * (a.y - p.y) - (a.x - p.x) * (b.y - a.y));
    const denominator = Math.hypot(b.x - a.x, b.y - a.y);
    return denominator === 0 ? 0 : numerator / denominator;
  } catch (e) {
    return 0;
  }
}

function circleFromThreePoints(p0, p1, p2) {
  try {
    const x1 = p0.x, y1 = p0.y;
    const x2 = p1.x, y2 = p1.y;
    const x3 = p2.x, y3 = p2.y;
    const d = 2 * (x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2));
    if (Math.abs(d) < 1e-9) return null;
    const ux = (x1 * x1 + y1 * y1) * (y2 - y3) + (x2 * x2 + y2 * y2) * (y3 - y1) + (x3 * x3 + y3 * y3) * (y1 - y2);
    const uy = (x1 * x1 + y1 * y1) * (x3 - x2) + (x2 * x2 + y2 * y2) * (x1 - x3) + (x3 * x3 + y3 * y3) * (x2 - x1);
    return { x: ux / d, y: uy / d, r: Math.hypot(x1 - (ux / d), y1 - (uy / d)) };
  } catch (e) {
    return null;
  }
}

function getArcMetrics(p0, p1, p2) {
  try {
    const sagitta = getPointToLineDistance(p1, p0, p2);
    const chordLength = getDistance(p0, p2);

    if (sagitta < chordLength * 0.001 || chordLength < 1e-9) {
      return { length: getDistance(p0, p1) + getDistance(p1, p2), chordArea: 0, isFlat: true };
    }

    const circ = circleFromThreePoints(p0, p1, p2);
    if (!circ || !Number.isFinite(circ.r)) {
      return { length: getDistance(p0, p1) + getDistance(p1, p2), chordArea: 0, isFlat: true };
    }

    const { x: cx, y: cy, r } = circ;
    const a0 = Math.atan2(p0.y - cy, p0.x - cx);
    const a1 = Math.atan2(p1.y - cy, p1.x - cx);
    const a2 = Math.atan2(p2.y - cy, p2.x - cx);

    const normalize = (a) => {
      while (a <= -Math.PI) a += 2 * Math.PI;
      while (a > Math.PI) a -= 2 * Math.PI;
      return a;
    };

    const totalTheta = Math.abs(normalize(a1 - a0)) + Math.abs(normalize(a2 - a1));
    const arcLength = r * totalTheta;
    const chordArea = 0.5 * r * r * (totalTheta - Math.sin(totalTheta));

    const cross = (p1.x - p0.x) * (p2.y - p0.y) - (p1.y - p0.y) * (p2.x - p0.x);
    return { length: arcLength, chordArea: cross > 0 ? chordArea : -chordArea, isFlat: false };
  } catch (e) {
    return { length: getDistance(p0, p1) + getDistance(p1, p2), chordArea: 0, isFlat: true };
  }
}

// Lateral surface of the 360° revolution generated by rotating `points`
// around the line through their two endpoints. Hidden segments (indices in
// `hiddenSegmentsIdx`) are excluded from the sum. Returns null when the axis
// is degenerate (P0 == Pn) so the caller can fall back to default behavior.
// Arcs (point.type === "circle") are treated as straight points — out of
// scope for v1.
function computeRevolutionSurface(points, meterByPx, hiddenSegmentsIdx = []) {
  const n = points?.length ?? 0;
  if (n < 2) return 0;
  const P0 = points[0];
  const Pn = points[n - 1];
  const ax = Pn.x - P0.x;
  const ay = Pn.y - P0.y;
  const axisLenPx = Math.hypot(ax, ay);
  if (axisLenPx < 1e-6) return null;
  const radiusPx = (p) =>
    Math.abs(ax * (P0.y - p.y) - (P0.x - p.x) * ay) / axisLenPx;
  let surfacePx2 = 0;
  for (let i = 0; i < n - 1; i++) {
    if (hiddenSegmentsIdx.includes(i)) continue;
    const r1 = radiusPx(points[i]);
    const r2 = radiusPx(points[i + 1]);
    const seg = Math.hypot(
      points[i + 1].x - points[i].x,
      points[i + 1].y - points[i].y
    );
    surfacePx2 += Math.PI * (r1 + r2) * seg;
  }
  return surfacePx2 * meterByPx * meterByPx;
}

/**
 * --- FONCTION PRINCIPALE ---
 */

export default function getAnnotationQties({
  annotation,
  meterByPx,
  profileLengthMeters,
}) {
  try {
    if (!annotation) return null;
    if (!meterByPx || !Number.isFinite(meterByPx) || meterByPx <= 0) return { enabled: false };

    if (annotation.type === "POINT") {
      const h = parseFloat(annotation.height);
      return {
        enabled: true,
        length: h && Number.isFinite(h) ? h : 0,
        surface: 0,
      };
    }

    if (annotation.type === "STRIP") {
      // Length: from the neutral/director line (original points as a POLYLINE)
      const neutralLineQty = getAnnotationQties({
        annotation: { ...annotation, type: "POLYLINE" },
        meterByPx,
      });
      const length = neutralLineQty?.length || 0;

      // EXTRUSION_PROFILE override: surface = profile_length × guide_length.
      // Hidden guide segments are already excluded by the neutral-line POLYLINE
      // path above.
      if (
        annotation.shape3D?.key === "EXTRUSION_PROFILE" &&
        profileLengthMeters != null
      ) {
        return {
          enabled: true,
          length,
          surface: profileLengthMeters * length,
        };
      }

      // Default surface: from the offset polygons (the ribbon)
      const polygons = getStripePolygons(annotation, meterByPx);
      const surface = polygons.reduce((acc, polygon) => {
        const qty = getAnnotationQties({ annotation: { ...polygon, type: "POLYGON" }, meterByPx });
        return acc + (qty?.surface || 0);
      }, 0);

      return {
        enabled: true,
        length,
        surface,
      };
    }

    const points = (annotation.points || []).filter(p => p && typeof p.x === "number");
    if (points.length < 2) return null;

    const closeLine = annotation.type === "POLYGON" || annotation.closeLine || false;

    const calculatePathMetrics = (pts, isClosed, hiddenSegments = []) => {
      try {
        let lengthPx = 0;
        let areaPx = 0;
        const n = pts.length;
        const limit = isClosed ? n : n - 1;

        let i = 0;
        // Sécurité contre boucle infinie : max d'itérations
        let iterations = 0;
        const MAX_ITER = n * 2;

        while (i < limit && iterations < MAX_ITER) {
          iterations++;
          const i0 = i % n;
          const i1 = (i + 1) % n;
          const i2 = (i + 2) % n;

          const p0 = pts[i0];
          const p1 = pts[i1];
          const p2 = pts[i2];

          if (!p0 || !p1) { i++; continue; }

          // Vérification SCS avec sécurité sur l'existence de p2
          const isArc = (p0.type !== "circle") &&
            (p1.type === "circle") &&
            (isClosed || i + 2 < n) &&
            (p2 && p2.type !== "circle");

          if (isArc) {
            const metrics = getArcMetrics(p0, p1, p2);
            if (metrics.isFlat) {
              if (!hiddenSegments.includes(i0)) lengthPx += getDistance(p0, p1);
              if (!hiddenSegments.includes(i1)) lengthPx += getDistance(p1, p2);
              if (isClosed) {
                areaPx += (p0.x * p1.y - p1.x * p0.y);
                areaPx += (p1.x * p2.y - p2.x * p1.y);
              }
            } else {
              if (!hiddenSegments.includes(i0) && !hiddenSegments.includes(i1)) {
                lengthPx += metrics.length;
              }
              if (isClosed) {
                areaPx += (p0.x * p2.y - p2.x * p0.y);
                areaPx += metrics.chordArea * 2;
              }
            }
            i += 2;
          } else {
            if (!hiddenSegments.includes(i0)) {
              lengthPx += getDistance(p0, p1);
            }
            if (isClosed) {
              areaPx += (p0.x * p1.y - p1.x * p0.y);
            }
            i += 1;
          }
        }
        return { lengthPx, areaPx: Math.abs(areaPx) / 2 };
      } catch (e) {
        console.log("error", e)
      }
    };

    const mainMetrics = calculatePathMetrics(points, closeLine, annotation.hiddenSegmentsIdx || []);
    let totalSurfacePx = mainMetrics.areaPx;
    let totalLengthPx = mainMetrics.lengthPx;

    if (closeLine && Array.isArray(annotation.cuts)) {
      annotation.cuts.forEach(cut => {
        const cutPoints = (cut.points || []).filter(p => p && typeof p.x === "number");
        if (cutPoints.length >= 3) {
          const cutMetrics = calculatePathMetrics(cutPoints, true, cut.hiddenSegmentsIdx || []);
          totalSurfacePx -= cutMetrics.areaPx;
          totalLengthPx += cutMetrics.lengthPx;
        }
      });
    }

    if (annotation.type === "POLYLINE") {
      if (annotation.shape3D?.key === "REVOLUTION") {
        const revSurfaceM2 = computeRevolutionSurface(
          points,
          meterByPx,
          annotation.hiddenSegmentsIdx || []
        );
        if (revSurfaceM2 != null) {
          return {
            enabled: true,
            length: totalLengthPx * meterByPx,
            surface: revSurfaceM2,
          };
        }
        // Degenerate axis (P0 = Pn) — fall through to default behavior.
      }
      if (
        annotation.shape3D?.key === "EXTRUSION_PROFILE" &&
        profileLengthMeters != null
      ) {
        // Hidden guide segments are already excluded from totalLengthPx.
        const guideLengthM = totalLengthPx * meterByPx;
        return {
          enabled: true,
          length: guideLengthM,
          surface: profileLengthMeters * guideLengthM,
        };
      }
      if (annotation.height) {
        totalSurfacePx = mainMetrics.lengthPx * (parseFloat(annotation.height) / meterByPx);
      }
    }

    const result = {
      enabled: true,
      length: totalLengthPx * meterByPx,
      surface: Math.max(0, totalSurfacePx) * (meterByPx * meterByPx),
    };

    // When per-vertex offsets are present (sloped top face), expose the
    // developed top-face surface as a separate field. The planar `surface`
    // above is left untouched so existing readers see no behavior change for
    // offset-free annotations and the planar footprint metric remains
    // available for offset-bearing annotations too.
    if (closeLine && hasPerVertexZOffsets(annotation)) {
      const cutsRings = (annotation.cuts || [])
        .map((c) => (c?.points || []).filter((p) => p && typeof p.x === "number"))
        .filter((r) => r.length >= 3);
      const innerPts = (annotation.innerPoints || []).filter(
        (p) => p && typeof p.x === "number"
      );
      const tri = triangulateAnnotationGeometry({
        contour: points,
        holes: cutsRings,
        innerPoints: innerPts,
        height: 0,
        verticalLift: 0,
        unitScale: meterByPx,
      });
      result.surfaceDeveloped = tri.areaTop;
    }

    return result;

  } catch (globalError) {
    console.error("Critical error in getAnnotationQties:", globalError);
    return { enabled: false, error: true };
  }
}